export const actionTypes = {
  PENDING_REQUEST: 'PENDING_REQUEST',
  SET_SESSION: 'SET_SESSION',
  RESET_SESSION: 'RESET_SESSION',
  SEARCH_ARTIST: 'SEARCH_ARTIST',
  SEARCH_ARTIST_SUCCESS: 'SEARCH_ARTIST_SUCCESS',
  FETCH_ALBUMS: 'FETCH_ALBUMS',
  FETCH_ALBUMS_SUCCESS: 'FETCH_ALBUMS_SUCCESS',
  REPEAT_REQUEST: 'REPEAT_REQUEST',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
  RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE'
};
